version: '3'

services:
  finance-manager:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    image: toshl_manager_local
    volumes:
      - .:/app
    env_file:
      - .env
